### ISSUE TITLE
Version 18.04 does not work

### ISSUE THREAD

**Issue by sbuljat** [play-rconf/play-rconf-dynamodb#1]
I'm trying to use version 18.04 in combination with 18.05 and 18.04 versions of play-rconf but none of them work. With 18.05 it shows that documents have been loaded but nothing gets updated:

`
[debug] application - [DynamoDB] KeyValueCfgObject[prospector.prospector.node.layer <- "xxx"]
[debug] application - [DynamoDB] KeyValueCfgObject[prospector.application.node.layer <- "api3"]
[debug] application - [DynamoDB] KeyValueCfgObject[prospector.node.layer <- "api4"]
[info] application - [DynamoDB] 0 configuration keys fetched and 0 files stored
`

When I switch to play-rconf 18.04 it shows no debug/info messages.

Any ideas?

**Comment by thibaultmeyer** [comment]
Hello,

thanks for issue report, could you try with this version?

```
resolvers += "jitpack" at "https://jitpack.io"

libraryDependencies += "com.github.play-rconf" % "play-rconf-dynamodb" % "f04c54eb36"
```

**Comment by sbuljat** [comment]
Hi,

its working the same, still same message in log.
`2018-10-04 12:41:08 INFO  play-rconf  - [DynamoDB] 0 configuration keys fetched and 0 files stored`

I've debugged the code and can see items are being loaded from DynamoDb, atomic counters are not set so that probably explains log message from above, but I have concerns about this part of code from ApplicationLoaderScala

`    initialBuilder
      .disableCircularProxies()
      .in(context.environment)
      .loadConfig(
        Configuration.apply(
          this.processAllProviders(localConfiguration.underlying)
        ) ++ localConfiguration
      )
`

This code loads config items but they're always overriden by local configuration. Is this intended behaviour or not?

**Comment by thibaultmeyer** [comment]
theoretically, the remote configuration is loaded and local configuration ​​is only used to complete the missing keys/values. We are using the Java version without any issues. The Scala version is probably bugged

**Comment by thibaultmeyer** [comment]
Hello @sbuljat ,

Just commit a fix on Scala version of play-rconf, could you try this commit ?

```
libraryDependencies += "com.github.play-rconf" % "play-rconf" % "8b5d551667"
libraryDependencies += "com.github.play-rconf" % "play-rconf-dynamodb" % "f04c54eb36"
```

**Comment by thibaultmeyer** [comment]
Hello @sbuljat ,

Fix commited on 5 oct 2018 is included in this new release.

```
libraryDependencies += "com.github.play-rconf" % "play-rconf" % "release~18.12"
libraryDependencies += "com.github.play-rconf" % "play-rconf-dynamodb" % "release~18.12"
```
